### ISSUE TITLE
报错：编译容量不足

### ISSUE THREAD

**Issue by Rbb666** [huming2207/daplink-air32f103#1]
你好，我使用 MDK 编译工程当 DAP_PACKET_SIZE 设置成 64 会导致 RAM 不足，请问是怎么解决的，谢谢？

**Comment by huming2207** [comment]
我用的GCC好像没提示什么问题，是ubuntu 22.04自带的，版本是10.3.1 20210621 (release) (15:10.3-2021.07-4) 

如果再有问题就把它改成16或者4好了，我这边试验了下大的buffer好像也没提升什么性能，估计瓶颈还是在USB 1.1上和SWD bitbanging上

**Comment by Rbb666** [comment]
> 我用的GCC好像没提示什么问题，是ubuntu 22.04自带的，版本是10.3.1 20210621 (release) (15:10.3-2021.07-4)
> 
> 如果再有问题就把它改成16或者4好了，我这边试验了下大的buffer好像也没提升什么性能，估计瓶颈还是在USB 1.1上和SWD bitbanging上

好的，谢谢
